#! /bin/sh
sxhkd &
$HOME/.config/bspwm/autostart &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor --reset-desktops 1 2 3 4
bspc desptop '^2' --layout monocle
# Make windows float on specific desktops
# https://github.com/baskerville/bspwm/issues/325
bspc subscribe node_manage | while read event monitor desktop nodeid ipid; do
	case "$desktop" in
		3|4)	bspc node "$nodeid" --state floating ;;
	esac
done &

bspc config border_width	4
bspc config window_gap		6
bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc config top_padding		24
#bspc config focus_follows_pointer	true
#bspc config history_aware_focus	true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a nitrogen state=floating
